version: '2'

services:
  cli:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    image: bkuhl/game-watcher:cli
    env_file: .env
    volumes:
      - ./public:/var/www/html/public