version: '2'

services:
  web:
    build:
      context: .
      dockerfile: infrastructure/nginx/Dockerfile
    image: bkuhl/game-watcher:web
    volumes:
      - ./infrastructure/nginx:/etc/nginx/conf.d
      - ./public:/var/www/html/public
    ports:
      - "80:80"